### ISSUE TITLE
Fatal error on regenerating thumbnails through WP CLI

### ISSUE THREAD

**Issue by robertnabbe** [cloudinary/cloudinary_wordpress#472]
Running `wp media regenerate` on the server while the Cloudinary plugin is activated will yield the following fatal error:
```php
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Cloudinary\Media::manage_sizes(), 2 passed in /sites/{-redacted-}/wp-includes/class-wp-hook.php on line 292 and exactly 3 expected in /sites/{-redacted-}/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php:2193
Stack trace:
#0 /sites/{-redacted-}/wp-includes/class-wp-hook.php(292): Cloudinary\Media->manage_sizes(Array, Array)
#1 /sites/{-redacted-}/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/media-command/src/Media_Command.php(828): apply_filters('intermediate_im...', Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/media-command/src/Media_Command.php(757): Media_Command->get_intermediate_sizes(false, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/media-command/src/Media_Command.php(658): Media_Command->get_intermediate_image_sizes_for_attachment('/sites/percprod...', false, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/ in /sites/{-redacted-}/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php on line 2193
```

Wordpress 5.7.2
Cloudinary Plugin 2.7.1

**Comment by victorli-cloudinary** [comment]
Hi there, thanks for reaching out to us! Would you be able to update to the latest version of the Cloudinary plugin and see if the issue persists?

**Comment by robertnabbe** [comment]
Updated plugin to 4.7.2. Forgot to mention previously that this website is part of a multi-site setup.

When running `wp media regenerate 68864`, I'm getting:
```php
Found 1 image to regenerate.
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Cloudinary\Media::manage_sizes(), 2 passed in /sites/{-redacted-}/wp-includes/class-wp-hook.php on line 292 and exactly 3 expected in /sites/{-redacted-}/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php:2196
Stack trace:
#0 /sites/{-redacted-}/wp-includes/class-wp-hook.php(292): Cloudinary\Media->manage_sizes(Array, Array)
#1 /sites/{-redacted-}/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/media-command/src/Media_Command.php(828): apply_filters('intermediate_im...', Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/media-command/src/Media_Command.php(757): Media_Command->get_intermediate_sizes(false, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/media-command/src/Media_Command.php(658): Media_Command->get_intermediate_image_sizes_for_attachment('/sites/percprod...', false, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/ in /sites/{-redacted-}/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php on line 2196
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```

**Comment by Vdeub-cloudinary** [comment]
Hi @robertnabbe, the latest plugin version is `2.7.5`, may I ask you to retry and confirm if you still get the issue or not?
Is it happening for all your images?

**Comment by Vdeub-cloudinary** [comment]
Hi @robertnabbe, our developer checked your issue and it seems it is an issue on WP-CLI itself. In this [line](https://github.com/wp-cli/media-command/blob/master/src/Media_Command.php#L828), the command is applying a WP Core [filter](https://developer.wordpress.org/reference/hooks/intermediate_image_sizes_advanced/) that requires 3 arguments. However, it’s missing the last argument, which is the $attachment_id and that’s what it’s causing this fatal error.

**Comment by robertnabbe** [comment]
Ah, I see, thanks for digging into that—updating the plugin is not going to fix the issue then :) Went and filed an issue on the wp-cli repo (https://github.com/wp-cli/media-command/issues/148). Hopefully this gets fixed soon. 

In the meantime, the work-around is to simply disable the plugin while `wp media regenerate` runs, which is not a big deal, but not elegant either.
