### ISSUE TITLE
Failing to sync all assets with `wp cloudinary sync`

### ISSUE THREAD

**Issue by gigo6000** [cloudinary/cloudinary_wordpress#657]
After running `wp cloudinary sync` I'm getting: 

```
$ wp cloudinary sync

╔═╗┬  ┌─┐┬ ┬┌┬┐┬┌┐┌┌─┐┬─┐┬ ┬  ╔═╗╦  ╦
║  │  │ ││ │ ││││││├─┤├┬┘└┬┘  ║  ║  ║
╚═╝┴─┘└─┘└─┘─┴┘┴┘└┘┴ ┴┴└─ ┴   ╚═╝╩═╝╩
Syncing assets
Syncing (1 of 14) : Logotype***OR@2x.png  7  % [==========>                                                                                                                                     ] 0:00 / 0:00PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in ***/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php:2272
Stack trace:
#0  ***/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-sync.php(225): Cloudinary\Media->get_process_logs()
#1  ***/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-push-sync.php(226): Cloudinary\Sync->log_sync_result()
#2  ***/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/traits/trait-cli.php(206): Cloudinary\Sync\Push_Sync->process_assets()
#3  ***/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/traits/trait-cli.php(164): Cloudinary\CLI->process_sync()
#4 ***/wp-content/plugins in /sites/blog/releases/20220111031354/wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php on line 2272
```

**Comment by gigo6000** [comment]
I created this PR: https://github.com/cloudinary/cloudinary_wordpress/pull/658

**Comment by Vdeub-cloudinary** [comment]
Hi @gigo6000,
Thanks for sharing the log and the PR, we'll review it and merge it if there is no problem.

**Comment by pereirinha** [comment]
Hi @gigo6000 

Thank you for reporting this and for the PR.

I did review it, and I'm afraid I've found a few issues in it. We'd be losing the history of past errored sync attempts with that approach. Also, there are other aspects to consider in migrating these logs from older data structures.

I did open PR #674, which handles this correctly, and it'd be great if you could have a go with it and validate this approach.

**Comment by gigo6000** [comment]
@pereirinha perfect, thanks
